sudo: required
services:
  - docker

language: node_js

node_js:
  - stable

install:
  - npm install

  # pull the container so that it is available for tests
  - docker run busybox sleep 0.1

script:
  - npm run cover-nyc
  - npm run lint
  #- ./cover-all.sh

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
